- name: Install OpenLDAP
  yum:
    name: "{{ item }}"
  with_items:
    - openldap-servers
    - openldap-clients

- name: Remove any previous installation files
  file:
    path: "{{ ansible_user_dir }}/easy_ldap_dir"
    state: absent

- name: Create directory for installation files
  file:
    path: "{{ ansible_user_dir }}/easy_ldap_dir"
    state: directory

- name: Create a separate directory folder for EASY
  file:
    path: /var/lib/ldap/easy
    state: directory
    owner: ldap
    group: ldap
    recurse: yes

- name: Start OpenLDAP
  service:
    name: slapd
    state: started

- name: Copy LDIF files to server
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/easy_ldap_dir/"
  with_items:
    - dans-schema.ldif
    - easy-schema.ldif
    - easy-db.ldif

- name: Copy templated LDIF files to server
  template:
    src: easy-basis.ldif
    dest: "{{ ansible_user_dir }}/easy_ldap_dir/"

# These schema's come pre-loaded in CentOS 6, but apparently not in CentOS 7
- name: Add referenced standard schema's if on CentOS 7
  command: ldapadd -v -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/{{ item }}
  with_items:
    - cosine.ldif
    - inetorgperson.ldif
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: Add schema's and base data to LDAP
  command: ldapadd -v -Y EXTERNAL -H ldapi:/// -f {{ ansible_user_dir }}/easy_ldap_dir/{{ item }}
  with_items:
    - dans-schema.ldif
    - easy-schema.ldif
    - easy-db.ldif

- name: Add basic entries to EASY database
  command: ldapadd -w secret -D cn=ldapadmin,dc=dans,dc=knaw,dc=nl
            -f {{ ansible_user_dir }}/easy_ldap_dir/easy-basis.ldif

- name: Generate password-hash for root user
  command: slappasswd -h {SSHA} -s {{ easy_ldap_dir_ldapadmin_password }}
  register: hash

- name: Generate ldif-script
  template:
    src: change-root-pw.ldif
    dest: "{{ ansible_user_dir }}/easy_ldap_dir/"

- name: Execute ldif-script
  command: chdir={{ ansible_user_dir }}/easy_ldap_dir/
           ldapadd -v -Y EXTERNAL -H ldapi:/// -f change-root-pw.ldif

- name: Generate password-hash for easyadmin
  command: slappasswd -h {SSHA} -s {{ easy_ldap_dir_easyadmin_password }}
  register: hash

- name: Generate ldif-script
  template:
    src: change-easyadmin-pw.ldif
    dest: "{{ ansible_user_dir }}/easy_ldap_dir/"
  when: ansible_local.easy_ldap.installed == False

- name: Execute ldif-script
  command: chdir={{ ansible_user_dir }}/easy_ldap_dir/
           ldapadd -w {{ easy_ldap_dir_ldapadmin_password }}
           -D cn=ldapadmin,dc=dans,dc=knaw,dc=nl -f change-easyadmin-pw.ldif
